# Generated by Django 3.2.12 on 2022-10-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='assignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avis.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='isOccupy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avis.session'),
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avis.user'),
        ),
        migrations.AddField(
            model_name='session',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='shot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
