# Generated by Django 3.2.12 on 2022-10-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_auto_20221021_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(default='63530cf72caf81d8870951c9', max_length=20),
        ),
    ]
