# Generated by Django 3.2.12 on 2022-10-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0003_alter_session_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(default='63530de2d98c62649cb6fbeb', max_length=50),
        ),
    ]
